import sqlite3
sqlite_conn = sqlite3.connect("src/sample.db")
def create_db():
    # Create a table in the SQLite database
    cursor = sqlite_conn.cursor()
    cursor.execute('''
        CREATE TABLE users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL
        );
    ''')
    sqlite_conn.commit()
    insert_query = '''
        INSERT INTO users (name, email) VALUES
        ('Alice Smith', 'alice.smith@example.com'),
        ('Bob Johnson', 'bob.johnson@example.com'),
        ('Charlie Brown', 'charlie.brown@example.com'),
        ('Diana Prince', 'diana.prince@example.com'),
        ('Eve Adams', 'eve.adams@example.com'),
        ('Frank White', 'frank.white@example.com'),
        ('Grace Taylor', 'grace.taylor@example.com'),
        ('Harry Wilson', 'harry.wilson@example.com'),
        ('Ivy Moore', 'ivy.moore@example.com'),
        ('Jack Davis', 'jack.davis@example.com'),
        ('Karen Miller', 'karen.miller@example.com'),
        ('Liam Garcia', 'liam.garcia@example.com'),
        ('Mia Rodriguez', 'mia.rodriguez@example.com'),
        ('Noah Martinez', 'noah.martinez@example.com'),
        ('Olivia Hernandez', 'olivia.hernandez@example.com'),
        ('Peter Lopez', 'peter.lopez@example.com'),
        ('Quinn Gonzales', 'quinn.gonzales@example.com'),
        ('Rachel Perez', 'rachel.perez@example.com'),
        ('Sam Roberts', 'sam.roberts@example.com'),
        ('Tina Campbell', 'tina.campbell@example.com'),
        ('Uma Scott', 'uma.scott@example.com'),
        ('Victor Green', 'victor.green@example.com'),
        ('Wendy Baker', 'wendy.baker@example.com'),
        ('Xavier Hall', 'xavier.hall@example.com'),
        ('Yara King', 'yara.king@example.com'),
        ('Zoe Wright', 'zoe.wright@example.com'),
        ('Adam Lewis', 'adam.lewis@example.com'),
        ('Bella Hill', 'bella.hill@example.com'),
        ('Caleb Clark', 'caleb.clark@example.com'),
        ('Daisy Young', 'daisy.young@example.com'),
        ('Ethan Allen', 'ethan.allen@example.com'),
        ('Fiona Nelson', 'fiona.nelson@example.com'),
        ('George Carter', 'george.carter@example.com'),
        ('Hannah Mitchell', 'hannah.mitchell@example.com'),
        ('Ian Roberts', 'ian.roberts@example.com'),
        ('Julia Phillips', 'julia.phillips@example.com'),
        ('Kyle Evans', 'kyle.evans@example.com'),
        ('Laura Turner', 'laura.turner@example.com'),
        ('Max Parker', 'max.parker@example.com'),
        ('Nora Collins', 'nora.collins@example.com'),
        ('Owen Edwards', 'owen.edwards@example.com'),
        ('Penny Stewart', 'penny.stewart@example.com'),
        ('Rex Morris', 'rex.morris@example.com'),
        ('Sarah Rogers', 'sarah.rogers@example.com'),
        ('Tom Reed', 'tom.reed@example.com'),
        ('Ursula Cook', 'ursula.cook@example.com'),
        ('Vance Morgan', 'vance.morgan@example.com'),
        ('Willow Bell', 'willow.bell@example.com'),
        ('Yolanda Ross', 'yolanda.ross@example.com'),
        ('Zachary Cox', 'zachary.cox@example.com'),
        ('Amy Ward', 'amy.ward@example.com'),
        ('Ben Peterson', 'ben.peterson@example.com'),
        ('Chloe Gray', 'chloe.gray@example.com'),
        ('David Ramirez', 'david.ramirez@example.com'),
        ('Ella James', 'ella.james@example.com'),
        ('Felix Watson', 'felix.watson@example.com'),
        ('Gigi Brooks', 'gigi.brooks@example.com'),
        ('Henry Kelly', 'henry.kelly@example.com'),
        ('Isabel Sanders', 'isabel.sanders@example.com'),
        ('Jason Price', 'jason.price@example.com'),
        ('Kimberly Bennett', 'kimberly.bennett@example.com'),
        ('Leo Wood', 'leo.wood@example.com'),
        ('Megan Barnes', 'megan.barnes@example.com'),
        ('Nathan Fisher', 'nathan.fisher@example.com'),
        ('Paige Cole', 'paige.cole@example.com'),
        ('Randy West', 'randy.west@example.com'),
        ('Sophie Long', 'sophie.long@example.com'),
        ('Tyler Foster', 'tyler.foster@example.com'),
        ('Violet Kim', 'violet.kim@example.com'),
        ('Walter Hayes', 'walter.hayes@example.com'),
        ('Xenia Perry', 'xenia.perry@example.com'),
        ('Yuri Powell', 'yuri.powell@example.com'),
        ('Zack Ryan', 'zack.ryan@example.com'),
        ('Anna Flores', 'anna.flores@example.com'),
        ('Benny Washington', 'benny.washington@example.com'),
        ('Cindy Butler', 'cindy.butler@example.com'),
        ('Daniel Jenkins', 'daniel.jenkins@example.com'),
        ('Emily Russell', 'emily.russell@example.com'),
        ('Fred Howard', 'fred.howard@example.com'),
        ('Gina Sanchez', 'gina.sanchez@example.com'),
        ('Hugh Coleman', 'hugh.coleman@example.com'),
        ('Irene Patterson', 'irene.patterson@example.com'),
        ('Jerry Bryant', 'jerry.bryant@example.com'),
        ('Kelly Alexander', 'kelly.alexander@example.com'),
        ('Louis Griffin', 'louis.griffin@example.com'),
        ('Maria Diaz', 'maria.diaz@example.com'),
        ('Nick Guzman', 'nick.guzman@example.com'),
        ('Pamela Ortiz', 'pamela.ortiz@example.com'),
        ('Ronnie Gibson', 'ronnie.gibson@example.com'),
        ('Susan Chapman', 'susan.chapman@example.com'),
        ('Terry Kennedy', 'terry.kennedy@example.com'),
        ('Una Marshall', 'una.marshall@example.com'),
        ('Vera Gordon', 'vera.gordon@example.com'),
        ('Willie Hanson', 'willie.hanson@example.com'),
        ('Yvonne Murray', 'yvonne.murray@example.com'),
        ('Zane Ford', 'zane.ford@example.com'),
        ('Brenda George', 'brenda.george@example.com'),
        ('Chris Simpson', 'chris.simpson@example.com'),
        ('Debra Lane', 'debra.lane@example.com'),
        ('Eric Stone', 'eric.stone@example.com'),
        ('Faith Fox', 'faith.fox@example.com'),
        ('Gary Rose', 'gary.rose@example.com'),
        ('Holly Dunn', 'holly.dunn@example.com'),
        ('Ivan Cole', 'ivan.cole@example.com'),
        ('Joy Palmer', 'joy.palmer@example.com'),
        ('Kevin Ruiz', 'kevin.ruiz@example.com'),
        ('Linda Schmidt', 'linda.schmidt@example.com');'''
    cursor.execute(insert_query)
    sqlite_conn.commit()
    print("Database and table created successfully.")
    cursor.close()
create_db()